apiVersion: v1
kind: Service
metadata:
 labels:
   name: mongo
 name: mongo
spec:
 ports:
  - port: 27017
    targetPort: 27017
 selector:
   name: mongo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
        - image: mongo
          name: mongo
          ports:
            - name: mongo
              containerPort: 27017
          volumeMounts:
            - name: mongo
              mountPath: /data/db
      volumes:
        - name: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: trellomicroservice
  labels:
    name: trellomicroservice
spec:
  type: LoadBalancer
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    name: trellomicroservice
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trellomicroservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: trellomicroservice
    spec:
      containers:
        - name: trellomicroservice
          image: "madmous/trellomicroservice"
          ports:
            - containerPort: 3001
