version: "2"
services:
  users-microservice:
    image: madmous/usersmicroservice
    ports:
      - "3002:3002"
    depends_on:
      - mysql
    links:
      - mysql
    restart: always
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: usersmicroservice
    restart: always