version: "2"
services:
  users-microservice:
    image: madmous/usersmicroservice
    ports:
      - "3002:3002"
    depends_on:
      - mysql
    networks:
      - usersdb
    restart: always
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - usersdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: usersmicroservice

volumes:
  mysql:

networks:
  usersdb: