version: "2"
services:
  web:
    build: .
    ports:
      - "3001:3001"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/mongodb:/data/db