version: "2"

services:
  trellomicroservice:
    image: madmous/trellomicroservice
    ports:
      - "3001:3001"
    networks:
      - trellousers
      - trellodb
    restart: always
    depends_on:
      - usersmicroservice
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    networks:
      - trellodb
    restart: always
  usersmicroservice:
    image: madmous/usersmicroservice
    ports:
      - "3002:3002"
    depends_on:
      - mysql
    networks:
      - trellousers
      - usersdb
    restart: always
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - usersdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: usersmicroservice

volumes:
  mongo:
  mysql:

networks:
  trellousers:
  trellodb:
  usersdb: