version: "2"

services:
  trello-microservice:
    image: madmous/trellomicroservice
    ports:
      - "3001:80"
    networks:
      - trellodb
      - trello
    restart: always
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    networks:
      - trellodb
    restart: always
  users-microservice:
    image: madmous/usersmicroservice
    ports:
      - "3002:3002"
    depends_on:
      - mysql
    networks:
      - usersdb
      - trello
    restart: always
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - usersdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: usersmicroservice

volumes:
  mongodb:
  mysql:

networks:
  trellodb:
  usersdb:
  trello: