version: "2"

services:
  trello-microservice:
    image: madmous/trellomicroservice
    ports:
      - "3001:80"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  users-microservice:
    image: madmous/usersmicroservice
    ports:
      - "3002:3002"
    depends_on:
      - mysql
    links:
      - mysql
      - trello-microservice
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: usersmicroservice