version: "2"
services:
  trello-microservice:
    image: madmous/trellomicroservice
    ports:
      - "3001:3001"
    networks:
      - trellodb
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    networks:
      - trellodb
    restart: always

volumes:
  mongo:

networks:
  trellodb: