version: "2"
services:
  trello-microservice:
    image: madmous/trellomicroservice
    ports:
      - "3001:80"
    networks:
      - trellodb
      - trello
    restart: always
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    networks:
      - trellodb
    restart: always

volumes:
  mongodb:

networks:
  trellodb:
  trello: