version: "2"
services:
  web:
    image: madmous/trellomicroservice
    ports:
      - "3001:80"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/mongodb:/data/db